version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "composer"
    open-pull-requests-limit: 10
    reviewers:
      - "odin-development"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5